version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/wallet_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        sleep 5
        createdb -U user test_wallet_db
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  create_test_db:
    build: .
    command: >
      sh -c "sleep 10 && psql -h db -U user -d wallet_db -c 'CREATE DATABASE test_wallet_db;'"
    depends_on:
      - db      
  migrations:
    build: .
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/wallet_db
    depends_on:
      db:
        condition: service_healthy
  tests:
    build: .
    command: pytest tests/ -v
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/test_wallet_db
    depends_on:
      db:
        condition: service_healthy   
volumes:
  postgres_data:

